config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  root 'homes#top'
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %w[show edit]

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_prams)
    @books = Book.all
    if @book.save
      flash['success'] = 'Book is created'
      redirect_to @book
    else
      render action: :index
    end
  end

  def show
  end

  def edit
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_prams)
      flash['success'] = 'Book is updated'
    else
      flash['failed'] = 'Book is not updated'
    end
    redirect_to book_path(@book)
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash['success'] = 'Book is deleted'
    else
      flash['failed'] = 'Book is not deleted'
    end
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_prams
    params.require(:book).permit(:title, :body).merge(user_id: current_user.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]

  def top
  end

  def home
    @book = Book.new
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %w[show edit update]

  def index
    @users = User.all
    @book = Book.new
  end

  def new
  end

  def create
  end

  def show
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash['success'] = 'User is Updated'
      redirect_to user_path(@user)
    else
      flash['failed'] = 'User is not Updated'
      redirect_to user_path(@user)
    end
  end

  def destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="container user">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Book</h3>
      <div class="edit-user__body">
        <%= form_with model: @book do |form|%>
          <div class="form-group">
            <%= form.label :Title %>
            <%= form.text_field :title, class: 'form-control'%>      
          </div>
          <div class="form-group">
            <%= form.label :Opiniton %>
            <%= form.text_field :body, class: 'form-control'%>      
          </div>
          <div class="form-group">
            <%= form.submit%>      
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container home">
  <%= render 'shared/errors', book: @book%>
  <div class="row">
    <%= render 'shared/user-side-bar', book: @book%>
    <div class="col-md-7 books-contaier">
      <div class="books__title">
        <h3>Books</h3>
      </div>
      <div class="books__body">
        <table class="table">
          <tr>
            <td></td>
            <td>Title</td>
            <td>Opinion</td>
          </tr>
          <% @books.each do |book|%>
            <tr>
              <td><%= attachment_image_tag book.user, :image, width: "40", height: "40" %></td>
              <td><%= link_to book_path(book) do%><%= book.title%><% end %></td>
              <td><%= book.body%></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container home">
  <div class="row">
    <%= render 'shared/user-side-bar', book: @book%>
    <div class="col-md-7 books-contaier">
      <div class="books__title">
        <h3>Book Detail</h3>
      </div>
      <div class="books__body">
        <table class="table">
          <tr>
            <td>
              <%= attachment_image_tag @book.user, :image, width: "40", height: "40" %>
              <br>
              <%= link_to user_path(@book.user) do %> <%= @book.user.name%> <%end%>
            </td>
            <td><%= link_to book_path(@book) do %> <%= @book.title %><%end%></td>
            <td><%= @book.body%></td>
            <% if @book.user.id == current_user.id %>
              <td><%= link_to edit_book_path(@book),class: "btn btn-sm btn-success" do %>Edit<%end%></td>
              <td><%= link_to book_path(@book),class: "btn btn-sm btn-danger", method: :delete, data: {confirm: '本当に消しますか？'} do %>Delete<%end%></td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/homes/about.html.erb
<div class="container about">
  <h3 class="about__title">Welcome to <i class="fas fa-book"></i>Bookers!</h3> 
</div>

app/views/homes/home.html.erb
<div class="container home">
  <div class="row">
    <%= render 'shared/user-side-bar', book: @book%>
    <div class="col-md-7 books-contaier">
      <div class="books__title">
        <h3>Books</h3>
      </div>
      <div class="books__body">
        <table class="table">
          <tr>
            <td>Title</td>
            <td>Opinion</td>
          </tr>
          <% current_user.books.each do |book|%>
            <tr>
              <td><%= book.title%></td>
              <td><%= book.body%></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container top">
  <h1 class="top__title">Welcome to <i class="fas fa-book"></i><span class="top-bookers">Bookers!!</span></h1>
  <p class="top__subtitle">
  In <i class="fas fa-book"></i>Bookers,<br><br>
  you can share and exchange your opinions , inpressions , and emotions <br>
  <br><br>
  about various books!  TESTTEST
  </p>

  <%= link_to new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' do %>
    Login In
  <% end %>
   <%= link_to new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' do %>
     Sign Up
   <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text-white" href="/">Boockers</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in?%>
        <li class="nav-item active">
          <%= link_to user_path(current_user), class: "nav-link text-white" do %>
            <i class="fas fa-book-open"></i>
              Home
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: "nav-link text-white" do %>
            <i class="fas fa-book-open"></i>
              Users
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to books_path, class: "nav-link text-white" do %>
            <i class="fas fa-book-open"></i>
              Books
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, class: "nav-link text-white", method: :delete do %>
            <i class="fas fa-book-open"></i>
              Log Out
          <%end%>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "/", class: "nav-link text-white" do %>
            <i class="fas fa-book-open"></i>
              Home
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to homes_about_path, class: "nav-link text-white" do %>
            <i class="fas fa-link"></i>
              About
          <%end%>        
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link text-white" do %>
            <i class="fas fa-book-open"></i>
              sign up
          <%end%>        
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link text-white" do %>
            <i class="fas fa-book-open"></i>
              Log In
          <%end%>        
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boockers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/84d345e866.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <% flash.each do |key, value|%>
      <%= content_tag(:div, value, class: key) %>
    <% end %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <footer>
      <p class="about__copyright">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if book.errors.any? %>
  <div class="failed">
    <%= book.errors.count %>errors prohibited this obj from being saved:<br>
    <% book.errors.full_messages.each do |message| %>
      <%= message %>
      <br>
    <% end %>
  </div>
<% end %>

app/views/shared/_user-side-bar.html.erb
<div class="col-md-5 user-container">
  <div class="user__title">
    <h3>User Info</h3>
  </div>
  <div class="user__info">
    <% if current_user.image.present? %>
      <%= attachment_image_tag current_user, :image, width: "100", height: "100" %>
    <% else %>
      <%= image_tag('no_image.png', width: "100", height: "100") %>      
    <% end %>
    <table class="table">
      <tr class="border-top">
        <td>name</td>
        <td><%= current_user.name%></td>
      </tr>
      <tr class="">
        <td>introduction</td>
        <td></td>
      </tr>
    </table>
    <div class="user-setting__link">
      <%= link_to edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  </div>
  <div class="book-form">
    <h3>New Book</h3>
    <%= form_with model: book, local: true do |form|%>
      <div class="form-group">
        <%= form.label :Title%>
        <%= form.text_field :title, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :Opinion%>
        <%= form.text_area :body, class: "form-control"%>          
      </div>
      <div class="form-group">
        <%= form.submit 'Create Book', class: "btn btn-success"%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="container user">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>User info</h3>
      <div class="edit-user__body">
        <%= form_with model: @user do |form|%>
          <div class="form-group">
            <%= form.label :Name %>
            <%= form.text_field :name, class: 'form-control'%>      
          </div>
          <div class="form-group">
            <%= form.label :Image %> <br>
            <%= form.attachment_field :image%>      
          </div>
          <div class="form-group">
            <%= form.label :Introduction %>
            <%= form.text_field :introduction, class: 'form-control'%>      
          </div>
          <div class="form-group">
            <%= form.submit%>      
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container home">
  <%= render 'shared/errors', book: @book%>
  <div class="row">
    <%= render 'shared/user-side-bar', book: @book%>
    <div class="col-md-7 books-contaier">
      <div class="books__title">
        <h3>Users</h3>
      </div>
      <div class="books__body">
        <table class="table">
          <tr>
            <td>Image</td>
            <td>Name</td>
            <td></td>
          </tr>
          <% @users.each do |user|%>
            <tr>
              <td><%= attachment_image_tag user, :image, width: "40", height: "40" %></td>
              <td><%= user.name%></td>
              <td><%= link_to user_path(user) do %> Show<% end %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container home">
  <div class="row">
    <%= render 'shared/user-side-bar', book: @book%>
    <div class="col-md-7 books-contaier">
      <div class="books__title">
        <h3>Books</h3>
      </div>
      <div class="books__body">
        <table class="table">
          <tr>
            <td></td>
            <td>Title</td>
            <td>Opinion</td>
          </tr>
          <% @user.books.each do |book|%>
            <tr>
              <td><%= attachment_image_tag @user, :image, width: "40", height: "40" %></td>
              <td><%= link_to book_path(book) do %> <%= book.title %><%end%></td>
              <td><%= book.body%></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>